"""The deterministic fill engine: values in, an exactly-filled official PDF out.

Forms are filled BY RULES, NEVER BY AI (business plan §4, issue #93), and
"done" for a form means matching the published PDF exactly — an off-spec form
gets bounced by the court. This module is the mechanical half of that promise:
given a `FormRelease` (core/form_templates.py) and values keyed by the spec's
logical field ids, it returns the official template with exactly those AcroForm
values set and NOTHING else changed — the page content streams stay
byte-identical to the court's own PDF, which is what the golden tests pin.

Deliberate properties:

- **Deterministic to the byte.** The same release and values always produce
  the same output bytes: no timestamps, no random ids, appearance streams
  generated by code, `NeedAppearances` left false. That is what lets the
  golden tests pin a sha256, and what makes a re-rendered packet diffable.
- **Values are verbatim.** The engine writes the strings it is given. What a
  money line looks like ("4,321.00"), how a date is spelled, which export
  state a stored enum maps to — those are the PROJECTION layer's decisions
  (the per-form mapping from case entities), not the engine's. The engine's
  own refusals are structural: an unknown field id, an export state the PDF
  does not declare, a district that is not in the dropdown, a value longer
  than the PDF's own character cap (the box would silently truncate it — on
  a court form that is data loss, so it is an error here).
- **The official PDFs' defects are first-class.** forms/README.md catalogues
  broken button groups (B106D row 2.4 exports `On` for all four options;
  B107 q26 merges a yes/no gate with its status into one exclusive group).
  For those, `WidgetStates` sets widget appearance states directly — checked
  boxes without a field value — because the field-value route is exactly
  what the defect breaks. Shared-widget fields (one field, boxes in two
  places) need nothing special: filling the field fills every widget, which
  is the PDF's own (defective) behaviour, faithfully reproduced.
- **A field the values omit stays untouched** — progressive fill is allowed;
  completeness ("every field this chapter's filing requires") is a separate
  pre-filing gate per case-data-model.md, not this module's concern.
- **A flat release is drawn, not filled** (issue #351). B2010 and B2030 are
  published with no AcroForm, so their specs claim overlay boxes
  (core/form_templates.OverlayBox) and this engine draws each value — text
  on a baseline in Helvetica, or an X across a printed checkbox — into ONE
  content stream appended to the page. The court's own page streams are
  never edited, which keeps the goldens' "official pages untouched" claim
  true for these forms too; the overlay is a separate stream that begins
  with a `% insolvia-overlay` marker and names every box it draws, so the
  goldens read it back field by field exactly as they read widgets. A flat
  release with nothing to draw ships the court's bytes verbatim.

This is a LIBRARY, callable from pipeline workers (ADR 0015): no Flask, no
endpoint, no I/O beyond the bytes it is handed. Packet assembly (9.6) calls
it once per form from a worker; a single-form render stays fast enough for a
synchronous caller too.
"""

from __future__ import annotations

import io
from collections.abc import Mapping
from dataclasses import dataclass

from pypdf import PdfWriter
from pypdf.generic import (
    ArrayObject,
    DictionaryObject,
    NameObject,
    PdfObject,
    StreamObject,
)

from .form_templates import FieldSpec, FormRelease, OverlayBox, Widget


class FormFillError(ValueError):
    """A value that cannot land on the form as asked. Carries every problem
    found, so a caller fixes one round trip, not one field per round trip."""

    def __init__(self, problems: list[str]) -> None:
        self.problems = tuple(problems)
        super().__init__("; ".join(problems))


@dataclass(frozen=True)
class Text:
    """A free-entry value for a text or choice widget, written verbatim."""

    value: str


@dataclass(frozen=True)
class Check:
    """Tick a single checkbox (its one export state). An unticked box is
    expressed by omitting the field, not by Check(False) — the template's
    default is already off, and 'explicitly no' vs 'not answered' is the
    projection's distinction to draw, on fields that print separate boxes."""

    on: bool = True


@dataclass(frozen=True)
class Option:
    """Select one export state of a radio group (or checkbox pair) by the
    PDF's exact export value — the spec's `options` list."""

    export: str


@dataclass(frozen=True)
class WidgetStates:
    """Set widget appearance states directly, bypassing the field value —
    the escape hatch for the official PDFs' broken button groups.

    `states` turns on every widget whose on-state is named (for groups whose
    states are distinct but wrongly exclusive, like B107 q26's merged
    gate+status). `indexes` turns on widgets by position — the order the
    field's widgets are encountered walking the document's pages — for
    groups whose states are indistinguishable (B106D row 2.4, where all four
    options export `On`).
    """

    states: tuple[str, ...] = ()
    indexes: tuple[int, ...] = ()


FieldFill = Text | Check | Option | WidgetStates
# One value for a single-widget field, or per-PDF-name values for a repeated
# field (two debtor columns, table rows) — the spec's `pdf` claim block is
# the address book, and FieldSpec.pdf_names lists the valid keys.
FieldValues = Mapping[str, "FieldFill | Mapping[str, FieldFill]"]

_TEXT_TYPES = frozenset(
    {
        "text",
        "money",
        "integer",
        "date",
        "year",
        "state",
        "district",
        "ssn_itin",
        "ein",
        "phone",
        "email",
        "signature",
    }
)


# --- overlay drawing (flat releases) ------------------------------------------

# The one font the overlay draws with: Helvetica, a standard-14 font every
# PDF reader carries, so nothing is embedded and the output stays small and
# deterministic. Values are written in WinAnsiEncoding (cp1252).
OVERLAY_FONT_SIZE = 10.0
_OVERLAY_MARKER = b"% insolvia-overlay\n"
_OVERLAY_FONT_KEY = "/Helv"

# Helvetica's advance widths for ASCII 32-126, per the Adobe AFM (1/1000 em).
# Used only to refuse a value wider than its printed space — the reader's own
# metrics render it, these just have to agree closely enough to catch the
# overflow, which for a standard-14 font they do exactly.
_HELVETICA_AFM = (
    "278 278 355 556 556 889 667 191 333 333 389 584 278 333 278 278 "  # space-/
    "556 556 556 556 556 556 556 556 556 556 278 278 584 584 584 556 "  # 0-?
    "1015 667 667 722 722 667 611 778 722 278 500 667 556 833 722 778 "  # @-O
    "667 778 722 667 611 722 667 944 667 667 611 278 278 278 469 556 "  # P-_
    "333 556 556 500 556 556 278 556 556 222 222 500 222 833 556 556 "  # `-o
    "556 556 333 500 278 556 500 722 500 500 500 334 260 334 584"  # p-~
)
_HELVETICA_WIDTHS = dict(
    zip(range(32, 127), map(int, _HELVETICA_AFM.split()), strict=True)
)


def helvetica_width(value: str, size: float = OVERLAY_FONT_SIZE) -> float:
    """The width, in points, `value` takes in Helvetica at `size` — the
    same estimate the projection layer wraps narratives against."""
    return sum(_HELVETICA_WIDTHS.get(ord(ch), 556) for ch in value) / 1000 * size


def _pdf_literal(value: str) -> bytes:
    """`value` as a PDF literal string in WinAnsiEncoding, escaped."""
    out = bytearray(b"(")
    for byte in value.encode("cp1252"):
        if byte in b"\\()":
            out += b"\\" + bytes([byte])
        elif 32 <= byte < 127:
            out.append(byte)
        else:
            out += f"\\{byte:03o}".encode("ascii")
    out += b")"
    return bytes(out)


def _check_box_text(
    box: OverlayBox, fill: Text, where: str, problems: list[str]
) -> None:
    if not fill.value:
        problems.append(f"{where}: empty value — omit the field to leave it blank")
        return
    if "\n" in fill.value or "\r" in fill.value:
        problems.append(f"{where}: value contains a line break")
    try:
        fill.value.encode("cp1252")
    except UnicodeEncodeError:
        problems.append(
            f"{where}: {fill.value!r} has a character Helvetica cannot draw"
        )
        return
    width = helvetica_width(fill.value)
    if width > box.w + 0.01:
        problems.append(
            f"{where}: {fill.value!r} is {width:.0f} points wide; the printed "
            f"space is {box.w:.0f}"
        )


def _validate_box(
    spec: FieldSpec, box: OverlayBox, fill: FieldFill, problems: list[str]
) -> None:
    where = f"{spec.id} -> {box.name!r}"
    if isinstance(fill, Text):
        if spec.type not in _TEXT_TYPES:
            problems.append(f"{where}: Text on a {spec.type} field")
        else:
            _check_box_text(box, fill, where, problems)
    elif isinstance(fill, Check):
        if not box.is_check:
            problems.append(f"{where}: Check on a {spec.type} field")
    else:
        problems.append(
            f"{where}: an overlay box takes Text or Check — a flat form has no "
            "export states to select"
        )


def _fmt(value: float) -> bytes:
    return f"{value:.2f}".encode("ascii")


def _overlay_stream(draws: list[tuple[OverlayBox, FieldFill]]) -> bytes:
    """The content stream for one page: the marker, then one named block
    per box, in box-name order so the bytes never depend on dict order."""
    lines = [_OVERLAY_MARKER]
    for box, fill in sorted(draws, key=lambda pair: pair[0].name):
        tag = box.name.encode("ascii")
        if isinstance(fill, Check):
            if not fill.on:
                continue
            assert box.h is not None  # validated: Check lands on a checkbox box
            inset = 2.5
            x1, y1 = box.x + inset, box.y + inset
            x2, y2 = box.x + box.w - inset, box.y + box.h - inset
            lines.append(
                b"% box:" + tag + b" check\n"
                b"q 0 G 1 w "
                + _fmt(x1)
                + b" "
                + _fmt(y1)
                + b" m "
                + _fmt(x2)
                + b" "
                + _fmt(y2)
                + b" l S "
                + _fmt(x1)
                + b" "
                + _fmt(y2)
                + b" m "
                + _fmt(x2)
                + b" "
                + _fmt(y1)
                + b" l S Q\n"
            )
        else:
            assert isinstance(fill, Text)  # validated: boxes take Text or Check
            lines.append(
                b"% box:" + tag + b"\n"
                b"BT "
                + _OVERLAY_FONT_KEY.encode("ascii")
                + b" "
                + _fmt(OVERLAY_FONT_SIZE)
                + b" Tf 1 0 0 1 "
                + _fmt(box.x)
                + b" "
                + _fmt(box.y)
                + b" Tm "
                + _pdf_literal(fill.value)
                + b" Tj ET\n"
            )
    return b"".join(lines)


def _ensure_overlay_font(page: DictionaryObject) -> None:
    """Declare Helvetica under /Helv in the page's font resources (a
    standard-14 font needs no embedding), leaving any existing entry alone."""
    resources_raw = page.get("/Resources")
    if resources_raw is None:
        resources = DictionaryObject()
        page[NameObject("/Resources")] = resources
    else:
        resources_obj = resources_raw.get_object()
        assert isinstance(resources_obj, DictionaryObject)  # PDF spec: a dict
        resources = resources_obj
    fonts_raw = resources.get("/Font")
    if fonts_raw is None:
        fonts = DictionaryObject()
        resources[NameObject("/Font")] = fonts
    else:
        fonts_obj = fonts_raw.get_object()
        assert isinstance(fonts_obj, DictionaryObject)  # PDF spec: a dict
        fonts = fonts_obj
    if _OVERLAY_FONT_KEY in fonts:
        return
    font = DictionaryObject()
    font[NameObject("/Type")] = NameObject("/Font")
    font[NameObject("/Subtype")] = NameObject("/Type1")
    font[NameObject("/BaseFont")] = NameObject("/Helvetica")
    font[NameObject("/Encoding")] = NameObject("/WinAnsiEncoding")
    fonts[NameObject(_OVERLAY_FONT_KEY)] = font


def _apply_overlay(
    writer: PdfWriter, draws: Mapping[str, tuple[OverlayBox, FieldFill]]
) -> None:
    """Append one overlay stream per drawn page. The page's existing
    /Contents — a stream or an array of them — is kept as-is ahead of it."""
    by_page: dict[int, list[tuple[OverlayBox, FieldFill]]] = {}
    for box, fill in draws.values():
        by_page.setdefault(box.page, []).append((box, fill))
    for page_number in sorted(by_page):
        page = writer.pages[page_number - 1]
        _ensure_overlay_font(page)
        stream = StreamObject()
        stream.set_data(_overlay_stream(by_page[page_number]))
        # pypdf exposes no public way to register a new indirect object; its
        # own page-merging code goes through this same method.
        appended = writer._add_object(stream)
        parts = ArrayObject()
        existing = page.raw_get("/Contents") if "/Contents" in page else None
        if existing is not None:
            resolved = existing.get_object()
            if isinstance(resolved, ArrayObject):
                parts.extend(resolved)
            else:
                parts.append(existing)
        parts.append(appended)
        page[NameObject("/Contents")] = parts


# --- widget validation ---------------------------------------------------------


def _check_text(widget: Widget, fill: Text, where: str, problems: list[str]) -> None:
    if not fill.value:
        problems.append(f"{where}: empty value — omit the field to leave it blank")
        return
    if "\r" in fill.value:
        problems.append(f"{where}: value contains a carriage return")
    if widget.max_len is not None and len(fill.value) > widget.max_len:
        problems.append(
            f"{where}: {fill.value!r} is longer than the PDF's "
            f"{widget.max_len}-character box — it would be truncated"
        )
    if widget.kind == "choice" and fill.value not in widget.choice_options:
        problems.append(
            f"{where}: {fill.value!r} is not an option of the {widget.name!r} dropdown"
        )


def _validate_one(
    spec: FieldSpec,
    widget: Widget,
    fill: FieldFill,
    problems: list[str],
) -> None:
    where = f"{spec.id} -> {widget.name!r}"
    if isinstance(fill, Text):
        if spec.type not in _TEXT_TYPES:
            problems.append(f"{where}: Text on a {spec.type} field")
        else:
            _check_text(widget, fill, where, problems)
    elif isinstance(fill, Check):
        if spec.type != "checkbox":
            problems.append(f"{where}: Check on a {spec.type} field")
        elif len(widget.states) != 1:
            problems.append(
                f"{where}: {len(widget.states)} export states — a group is "
                "selected with Option, not Check"
            )
    elif isinstance(fill, Option):
        if spec.type not in ("radio", "checkbox"):
            problems.append(f"{where}: Option on a {spec.type} field")
        elif fill.export not in widget.states:
            problems.append(
                f"{where}: export {fill.export!r} is not one of the PDF's "
                f"states {sorted(widget.states)}"
            )
    elif isinstance(fill, WidgetStates):
        if spec.type not in ("radio", "checkbox"):
            problems.append(f"{where}: WidgetStates on a {spec.type} field")
        else:
            for state in fill.states:
                if state not in widget.states:
                    problems.append(
                        f"{where}: state {state!r} is not one of the PDF's "
                        f"states {sorted(widget.states)}"
                    )
        if not fill.states and not fill.indexes:
            problems.append(f"{where}: WidgetStates selects nothing")


def _per_widget(
    release: FormRelease, values: FieldValues
) -> dict[str, tuple[FieldSpec, FieldFill]]:
    """Validate and flatten to one instruction per PDF field name."""
    problems: list[str] = []
    flat: dict[str, tuple[FieldSpec, FieldFill]] = {}
    for field_id, fill in values.items():
        try:
            spec = release.field(field_id)
        except KeyError:
            problems.append(f"{field_id}: not a field of {release.release_id}")
            continue
        if isinstance(fill, Mapping):
            entries = dict(fill)
            unknown = sorted(set(entries) - set(spec.pdf_names))
            if unknown:
                problems.append(
                    f"{field_id}: not among this field's PDF fields: {unknown}"
                )
                continue
        else:
            if len(spec.pdf_names) != 1:
                problems.append(
                    f"{field_id}: repeats across {len(spec.pdf_names)} PDF "
                    "fields — address instances by PDF name"
                )
                continue
            entries = {spec.pdf_names[0]: fill}
        for name, one in entries.items():
            if name in release.boxes:
                _validate_box(spec, release.boxes[name], one, problems)
            else:
                _validate_one(spec, release.widgets[name], one, problems)
            flat[name] = (spec, one)
    if problems:
        raise FormFillError(sorted(problems))
    return flat


def _widget_field_name(annotation: DictionaryObject) -> str | None:
    """The fully qualified field name a widget annotation belongs to."""
    parts: list[str] = []
    node: PdfObject | None = annotation
    while node is not None:
        obj = node.get_object()
        if not isinstance(obj, DictionaryObject):  # pragma: no cover - defensive
            break
        title = obj.get("/T")
        if title is not None:
            parts.append(str(title))
        node = obj.get("/Parent")
    if not parts:
        return None
    return ".".join(reversed(parts))


def _on_state(annotation: DictionaryObject) -> str | None:
    """The one non-Off appearance state a button widget can show."""
    ap = annotation.get("/AP")
    if ap is None:
        return None
    normal = ap.get_object().get("/N")
    if normal is None:
        return None
    states = [str(s).lstrip("/") for s in normal.get_object()]
    on = [s for s in states if s != "Off"]
    return on[0] if len(on) == 1 else None


def _apply_widget_states(
    writer: PdfWriter, targets: Mapping[str, WidgetStates]
) -> None:
    """Turn on widget appearances directly — the broken-group route.

    Widgets are indexed in the order encountered walking the document's
    pages, which is the printed order for these forms. No field /V is set:
    the group's value cannot express the selection (that is the defect), so
    the ticks live in the appearance states alone — exactly what printing
    or flattening reads.
    """
    seen: dict[str, int] = dict.fromkeys(targets, 0)
    for page in writer.pages:
        for ref in page.get("/Annots") or []:
            annotation = ref.get_object()
            if not isinstance(annotation, DictionaryObject):
                continue  # pragma: no cover - defensive
            name = _widget_field_name(annotation)
            if name not in seen:
                continue
            index = seen[name]
            seen[name] = index + 1
            wanted = targets[name]
            state = _on_state(annotation)
            if state is None:
                continue  # pragma: no cover - buttons always carry one
            if index in wanted.indexes or state in wanted.states:
                annotation[NameObject("/AS")] = NameObject(f"/{state}")


def _field_nodes(writer: PdfWriter) -> list[tuple[DictionaryObject, str]]:
    """Every field node that owns widgets, with its fully qualified name —
    the annotation itself where it carries /FT and /T, its parent otherwise
    (mirroring pypdf's own resolution)."""
    nodes: dict[int, tuple[DictionaryObject, str]] = {}
    for page in writer.pages:
        for ref in page.get("/Annots") or []:
            annotation = ref.get_object()
            if not isinstance(annotation, DictionaryObject):
                continue  # pragma: no cover - defensive
            if "/FT" in annotation and "/T" in annotation:
                node = annotation
            else:
                parent = annotation.get("/Parent")
                if parent is None:
                    continue  # pragma: no cover - defensive
                node = parent.get_object()
            qualified = _widget_field_name(annotation)
            if qualified is not None:
                nodes[id(node)] = (node, qualified)
    return list(nodes.values())


def _apply_field_updates(writer: PdfWriter, field_updates: Mapping[str, str]) -> None:
    """Set each value on exactly the field its QUALIFIED name addresses.

    pypdf's `update_page_form_field_values` also matches a key against every
    field node's own partial /T, so on a form with hierarchical names a
    top-level field called "3" would broadcast into "2.3" and "check 2.3" —
    B106C's statute column collides exactly like this. Each key is therefore
    applied on its own, with any OTHER field node whose partial /T equals
    the key renamed out of the way for the duration and restored afterwards
    (the same object is put back, so the output bytes carry no trace).
    """
    nodes = _field_nodes(writer)
    sentinel = NameObject("/__insolvia_fill_shield__")
    for key, value in field_updates.items():
        shielded: list[tuple[DictionaryObject, PdfObject]] = []
        for node, qualified in nodes:
            if (
                qualified != key
                and node.get("/T") is not None
                and str(node["/T"]) == key
            ):
                shielded.append((node, node.raw_get("/T")))
                node[NameObject("/T")] = sentinel
        try:
            for page in writer.pages:
                # pypdf updates the widgets present on each page; a field
                # whose widgets span pages (B101's chapter boxes on pages 1
                # and 3) is simply updated on each of them.
                writer.update_page_form_field_values(
                    page, {key: value}, auto_regenerate=False
                )
        finally:
            for node, original in shielded:
                node[NameObject("/T")] = original


def fill_form(release: FormRelease, values: FieldValues) -> bytes:
    """Fill the release's official template with `values`, deterministically.

    Raises FormFillError (listing every problem) rather than writing a form
    that disagrees with the PDF's own contract. Returns the filled PDF bytes;
    the caller owns where they go.
    """
    flat = _per_widget(release, values)

    field_updates: dict[str, str] = {}
    appearance_targets: dict[str, WidgetStates] = {}
    draws: dict[str, tuple[OverlayBox, FieldFill]] = {}
    for name, (_spec, fill) in flat.items():
        if name in release.boxes:
            draws[name] = (release.boxes[name], fill)
        elif isinstance(fill, Text):
            field_updates[name] = fill.value
        elif isinstance(fill, Check):
            if fill.on:
                field_updates[name] = f"/{release.widgets[name].states[0]}"
        elif isinstance(fill, Option):
            field_updates[name] = f"/{fill.export}"
        elif isinstance(fill, WidgetStates):
            appearance_targets[name] = fill

    if release.is_flat and not draws:
        # A notice with nothing to draw: the court's own bytes, untouched —
        # nothing to re-serialise, and the output IS the vendored template.
        return release.template_pdf

    writer = PdfWriter(clone_from=io.BytesIO(release.template_pdf))
    if field_updates:
        _apply_field_updates(writer, field_updates)
    if appearance_targets:
        _apply_widget_states(writer, appearance_targets)
    if draws:
        _apply_overlay(writer, draws)

    out = io.BytesIO()
    writer.write(out)
    return out.getvalue()
