"""The deterministic fill engine: values in, an exactly-filled official PDF out.

Forms are filled BY RULES, NEVER BY AI (business plan §4, issue #93), and
"done" for a form means matching the published PDF exactly — an off-spec form
gets bounced by the court. This module is the mechanical half of that promise:
given a `FormRelease` (core/form_templates.py) and values keyed by the spec's
logical field ids, it returns the official template with exactly those AcroForm
values set and NOTHING else changed — the page content streams stay
byte-identical to the court's own PDF, which is what the golden tests pin.

Deliberate properties:

- **Deterministic to the byte.** The same release and values always produce
  the same output bytes: no timestamps, no random ids, appearance streams
  generated by code, `NeedAppearances` left false. That is what lets the
  golden tests pin a sha256, and what makes a re-rendered packet diffable.
- **Values are verbatim.** The engine writes the strings it is given. What a
  money line looks like ("4,321.00"), how a date is spelled, which export
  state a stored enum maps to — those are the PROJECTION layer's decisions
  (the per-form mapping from case entities), not the engine's. The engine's
  own refusals are structural: an unknown field id, an export state the PDF
  does not declare, a district that is not in the dropdown, a value longer
  than the PDF's own character cap (the box would silently truncate it — on
  a court form that is data loss, so it is an error here).
- **The official PDFs' defects are first-class.** forms/README.md catalogues
  broken button groups (B106D row 2.4 exports `On` for all four options;
  B107 q26 merges a yes/no gate with its status into one exclusive group).
  For those, `WidgetStates` sets widget appearance states directly — checked
  boxes without a field value — because the field-value route is exactly
  what the defect breaks. Shared-widget fields (one field, boxes in two
  places) need nothing special: filling the field fills every widget, which
  is the PDF's own (defective) behaviour, faithfully reproduced.
- **A field the values omit stays untouched** — progressive fill is allowed;
  completeness ("every field this chapter's filing requires") is a separate
  pre-filing gate per case-data-model.md, not this module's concern.

This is a LIBRARY, callable from pipeline workers (ADR 0015): no Flask, no
endpoint, no I/O beyond the bytes it is handed. Packet assembly (9.6) calls
it once per form from a worker; a single-form render stays fast enough for a
synchronous caller too.
"""

from __future__ import annotations

import io
from collections.abc import Mapping
from dataclasses import dataclass

from pypdf import PdfWriter
from pypdf.generic import DictionaryObject, NameObject, PdfObject

from .form_templates import FieldSpec, FormRelease, Widget


class FormFillError(ValueError):
    """A value that cannot land on the form as asked. Carries every problem
    found, so a caller fixes one round trip, not one field per round trip."""

    def __init__(self, problems: list[str]) -> None:
        self.problems = tuple(problems)
        super().__init__("; ".join(problems))


@dataclass(frozen=True)
class Text:
    """A free-entry value for a text or choice widget, written verbatim."""

    value: str


@dataclass(frozen=True)
class Check:
    """Tick a single checkbox (its one export state). An unticked box is
    expressed by omitting the field, not by Check(False) — the template's
    default is already off, and 'explicitly no' vs 'not answered' is the
    projection's distinction to draw, on fields that print separate boxes."""

    on: bool = True


@dataclass(frozen=True)
class Option:
    """Select one export state of a radio group (or checkbox pair) by the
    PDF's exact export value — the spec's `options` list."""

    export: str


@dataclass(frozen=True)
class WidgetStates:
    """Set widget appearance states directly, bypassing the field value —
    the escape hatch for the official PDFs' broken button groups.

    `states` turns on every widget whose on-state is named (for groups whose
    states are distinct but wrongly exclusive, like B107 q26's merged
    gate+status). `indexes` turns on widgets by position — the order the
    field's widgets are encountered walking the document's pages — for
    groups whose states are indistinguishable (B106D row 2.4, where all four
    options export `On`).
    """

    states: tuple[str, ...] = ()
    indexes: tuple[int, ...] = ()


FieldFill = Text | Check | Option | WidgetStates
# One value for a single-widget field, or per-PDF-name values for a repeated
# field (two debtor columns, table rows) — the spec's `pdf` claim block is
# the address book, and FieldSpec.pdf_names lists the valid keys.
FieldValues = Mapping[str, "FieldFill | Mapping[str, FieldFill]"]

_TEXT_TYPES = frozenset(
    {
        "text",
        "money",
        "integer",
        "date",
        "year",
        "state",
        "district",
        "ssn_itin",
        "ein",
        "phone",
        "email",
        "signature",
    }
)


def _check_text(widget: Widget, fill: Text, where: str, problems: list[str]) -> None:
    if not fill.value:
        problems.append(f"{where}: empty value — omit the field to leave it blank")
        return
    if "\r" in fill.value:
        problems.append(f"{where}: value contains a carriage return")
    if widget.max_len is not None and len(fill.value) > widget.max_len:
        problems.append(
            f"{where}: {fill.value!r} is longer than the PDF's "
            f"{widget.max_len}-character box — it would be truncated"
        )
    if widget.kind == "choice" and fill.value not in widget.choice_options:
        problems.append(
            f"{where}: {fill.value!r} is not an option of the {widget.name!r} dropdown"
        )


def _validate_one(
    spec: FieldSpec,
    widget: Widget,
    fill: FieldFill,
    problems: list[str],
) -> None:
    where = f"{spec.id} -> {widget.name!r}"
    if isinstance(fill, Text):
        if spec.type not in _TEXT_TYPES:
            problems.append(f"{where}: Text on a {spec.type} field")
        else:
            _check_text(widget, fill, where, problems)
    elif isinstance(fill, Check):
        if spec.type != "checkbox":
            problems.append(f"{where}: Check on a {spec.type} field")
        elif len(widget.states) != 1:
            problems.append(
                f"{where}: {len(widget.states)} export states — a group is "
                "selected with Option, not Check"
            )
    elif isinstance(fill, Option):
        if spec.type not in ("radio", "checkbox"):
            problems.append(f"{where}: Option on a {spec.type} field")
        elif fill.export not in widget.states:
            problems.append(
                f"{where}: export {fill.export!r} is not one of the PDF's "
                f"states {sorted(widget.states)}"
            )
    elif isinstance(fill, WidgetStates):
        if spec.type not in ("radio", "checkbox"):
            problems.append(f"{where}: WidgetStates on a {spec.type} field")
        else:
            for state in fill.states:
                if state not in widget.states:
                    problems.append(
                        f"{where}: state {state!r} is not one of the PDF's "
                        f"states {sorted(widget.states)}"
                    )
        if not fill.states and not fill.indexes:
            problems.append(f"{where}: WidgetStates selects nothing")


def _per_widget(
    release: FormRelease, values: FieldValues
) -> dict[str, tuple[FieldSpec, FieldFill]]:
    """Validate and flatten to one instruction per PDF field name."""
    problems: list[str] = []
    flat: dict[str, tuple[FieldSpec, FieldFill]] = {}
    for field_id, fill in values.items():
        try:
            spec = release.field(field_id)
        except KeyError:
            problems.append(f"{field_id}: not a field of {release.release_id}")
            continue
        if isinstance(fill, Mapping):
            entries = dict(fill)
            unknown = sorted(set(entries) - set(spec.pdf_names))
            if unknown:
                problems.append(
                    f"{field_id}: not among this field's PDF fields: {unknown}"
                )
                continue
        else:
            if len(spec.pdf_names) != 1:
                problems.append(
                    f"{field_id}: repeats across {len(spec.pdf_names)} PDF "
                    "fields — address instances by PDF name"
                )
                continue
            entries = {spec.pdf_names[0]: fill}
        for name, one in entries.items():
            _validate_one(spec, release.widgets[name], one, problems)
            flat[name] = (spec, one)
    if problems:
        raise FormFillError(sorted(problems))
    return flat


def _widget_field_name(annotation: DictionaryObject) -> str | None:
    """The fully qualified field name a widget annotation belongs to."""
    parts: list[str] = []
    node: PdfObject | None = annotation
    while node is not None:
        obj = node.get_object()
        if not isinstance(obj, DictionaryObject):  # pragma: no cover - defensive
            break
        title = obj.get("/T")
        if title is not None:
            parts.append(str(title))
        node = obj.get("/Parent")
    if not parts:
        return None
    return ".".join(reversed(parts))


def _on_state(annotation: DictionaryObject) -> str | None:
    """The one non-Off appearance state a button widget can show."""
    ap = annotation.get("/AP")
    if ap is None:
        return None
    normal = ap.get_object().get("/N")
    if normal is None:
        return None
    states = [str(s).lstrip("/") for s in normal.get_object()]
    on = [s for s in states if s != "Off"]
    return on[0] if len(on) == 1 else None


def _apply_widget_states(
    writer: PdfWriter, targets: Mapping[str, WidgetStates]
) -> None:
    """Turn on widget appearances directly — the broken-group route.

    Widgets are indexed in the order encountered walking the document's
    pages, which is the printed order for these forms. No field /V is set:
    the group's value cannot express the selection (that is the defect), so
    the ticks live in the appearance states alone — exactly what printing
    or flattening reads.
    """
    seen: dict[str, int] = dict.fromkeys(targets, 0)
    for page in writer.pages:
        for ref in page.get("/Annots") or []:
            annotation = ref.get_object()
            if not isinstance(annotation, DictionaryObject):
                continue  # pragma: no cover - defensive
            name = _widget_field_name(annotation)
            if name not in seen:
                continue
            index = seen[name]
            seen[name] = index + 1
            wanted = targets[name]
            state = _on_state(annotation)
            if state is None:
                continue  # pragma: no cover - buttons always carry one
            if index in wanted.indexes or state in wanted.states:
                annotation[NameObject("/AS")] = NameObject(f"/{state}")


def fill_form(release: FormRelease, values: FieldValues) -> bytes:
    """Fill the release's official template with `values`, deterministically.

    Raises FormFillError (listing every problem) rather than writing a form
    that disagrees with the PDF's own contract. Returns the filled PDF bytes;
    the caller owns where they go.
    """
    flat = _per_widget(release, values)

    field_updates: dict[str, str] = {}
    appearance_targets: dict[str, WidgetStates] = {}
    for name, (_spec, fill) in flat.items():
        if isinstance(fill, Text):
            field_updates[name] = fill.value
        elif isinstance(fill, Check):
            if fill.on:
                field_updates[name] = f"/{release.widgets[name].states[0]}"
        elif isinstance(fill, Option):
            field_updates[name] = f"/{fill.export}"
        elif isinstance(fill, WidgetStates):
            appearance_targets[name] = fill

    writer = PdfWriter(clone_from=io.BytesIO(release.template_pdf))
    if field_updates:
        for page in writer.pages:
            # pypdf updates the widgets present on each page; a field whose
            # widgets span pages (B101's chapter boxes on pages 1 and 3) is
            # simply updated on each of them.
            writer.update_page_form_field_values(
                page, dict(field_updates), auto_regenerate=False
            )
    if appearance_targets:
        _apply_widget_states(writer, appearance_targets)

    out = io.BytesIO()
    writer.write(out)
    return out.getvalue()
