// GENERATED by tool/render-brand-theme.ts from brand/colors.json — DO NOT EDIT.
// Regenerate with `npm run tokens`; `npm run tokens:check` gates it.
//
// Insolvia's brand overrides for @insolvia-ai/design-system, whose base
// theme is deliberately unbranded from tokens 0.5.0 on. Only the roles
// Insolvia moves are here; everything else falls through to the package.
//
// The hover/active states are stated rather than derived because React
// Native has no live blend — `ThemeProvider` merges values, not formulas,
// so overriding `primary` alone would leave its hover behind. The web
// surfaces omit them for the opposite reason. See brand/colors.json.

export const brandColors = {
  light: {
    accent: '#B8863B',
    accentHover: '#A27634',
    bg: '#FAF9F6',
    brand: '#0B2A4A',
    card: '#FFFFFF',
    ink: '#141A1F',
    line: '#C9D0D8',
    muted: '#5A6672',
    primary: '#0B2A4A',
    primaryActive: '#09223B',
    primaryHover: '#0A2541',
    primaryText: '#FFFFFF',
    surfaceAlt: '#EFEDE6',
  },
  dark: {
    accent: '#D2A857',
    accentHover: '#D7B26B',
    bg: '#071B31',
    brand: '#FFFFFF',
    card: '#141A1F',
    ink: '#FAF9F6',
    line: '#FFFFFF33',
    muted: '#C9D0D8',
    primary: '#D2A857',
    primaryActive: '#B08D49',
    primaryHover: '#D7B26B',
    primaryText: '#071B31',
    surfaceAlt: '#0B2A4A',
  },
} as const;
