// GENERATED by tool/render-brand-theme.ts from brand/colors.json — DO NOT EDIT.
// Regenerate with `npm run tokens`; `npm run tokens:check` gates it.
//
// Insolvia's brand overrides for @insolvia-ai/design-system, whose base
// theme is deliberately unbranded from tokens 0.5.0 on. Only the roles
// Insolvia moves are here; everything else falls through to the package.
//
// The hover/active states are stated rather than derived because React
// Native has no live blend — `ThemeProvider` merges values, not formulas,
// so overriding `primary` alone would leave its hover behind. The web
// surfaces omit them for the opposite reason. See brand/colors.json.

export const brandColors = {
  light: {
    accent: '#8A6524',
    accentHover: '#75551E',
    bg: '#FAFAF9',
    brand: '#0F0E0D',
    card: '#FFFFFF',
    danger: '#8C4A3F',
    ink: '#0F0E0D',
    line: '#E4E2DE',
    muted: '#706D66',
    primary: '#1A1917',
    primaryActive: '#0A0908',
    primaryHover: '#0F0E0D',
    primaryText: '#FAFAF9',
    success: '#3F6B52',
    surfaceAlt: '#F1F0ED',
    warning: '#8A6524',
  },
  dark: {
    accent: '#C6A059',
    accentHover: '#D2B074',
    bg: '#100F0E',
    brand: '#F5F4F2',
    card: '#1A1917',
    danger: '#C88C80',
    ink: '#F5F4F2',
    line: '#2E2C29',
    muted: '#9A968F',
    primary: '#F5F4F2',
    primaryActive: '#DAD7D2',
    primaryHover: '#FFFFFF',
    primaryText: '#100F0E',
    success: '#7FA98D',
    surfaceAlt: '#242220',
    warning: '#C6A059',
  },
} as const;

/**
 * The brand type families, from brand/fonts.json.
 *
 * Two consumers, for the same reason `brandColors` has two: the app's own
 * `useTheme()` reads them as `typography`, and `ThemeProvider` takes them as
 * `fonts` so the design system's native leaves follow. A family stated in
 * only one of the two renders branded headings over system body text.
 *
 * Naming a family does not load it. The faces are self-hosted .woff2 under
 * `public/fonts`, declared @font-face in `public/index.html`.
 */
export const brandFonts = {
  heading: '"Cormorant Garamond", Georgia, "Times New Roman", serif',
  body: '"Open Sans", ui-sans-serif, system-ui, sans-serif',
  mono: '"IBM Plex Mono", ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, "Liberation Mono", "Courier New", monospace',
} as const;

/**
 * The brand corner radii, from brand/radii.json.
 *
 * Two consumers again: the app's own `useTheme()` reads them as `radii`,
 * and `ThemeProvider` takes them so the package's native leaves follow.
 * `pill` is absent because the package refuses to theme it — the leaves
 * that draw a capsule compute their own.
 */
export const brandRadii = {
  none: 0,
  xs: 3,
  sm: 4,
  md: 6,
  lg: 10,
} as const;
