// GENERATED by tool/render-brand-theme.ts from brand/colors.json — DO NOT EDIT.
// Regenerate with `npm run tokens`; `npm run tokens:check` gates it.
//
// Insolvia's brand overrides for @insolvia-ai/design-system, whose base
// theme is deliberately unbranded from tokens 0.5.0 on. Only the roles
// Insolvia moves are here; everything else falls through to the package.
//
// The hover/active states are stated rather than derived because React
// Native has no live blend — `ThemeProvider` merges values, not formulas,
// so overriding `primary` alone would leave its hover behind. The web
// surfaces omit them for the opposite reason. See brand/colors.json.

export const brandColors = {
  light: {
    accent: '#B8863B',
    accentHover: '#A27634',
    bg: '#FAF9F6',
    brand: '#0B2A4A',
    card: '#FFFFFF',
    ink: '#141A1F',
    line: '#C9D0D8',
    muted: '#5A6672',
    primary: '#0B2A4A',
    primaryActive: '#09223B',
    primaryHover: '#0A2541',
    primaryText: '#FFFFFF',
    surfaceAlt: '#EFEDE6',
  },
  dark: {
    accent: '#D2A857',
    accentHover: '#D7B26B',
    bg: '#0B1622',
    brand: '#E9EEF4',
    card: '#122032',
    ink: '#E9EEF4',
    line: '#2E4459',
    muted: '#889CB1',
    primary: '#D2A857',
    primaryActive: '#B08D49',
    primaryHover: '#D7B26B',
    primaryText: '#0B1622',
    surfaceAlt: '#1B2D42',
    warning: '#E0913C',
  },
} as const;
