// Renders `packages/insolvia_tokens/tokens.json` into every consuming stack.
//
//   npm run tokens
//   npm run tokens:check
//
// `--check` regenerates in memory and exits non-zero if any committed output
// has drifted from the JSON, so CI can gate hand-edits to generated files.
//
// Deliberately dependency-free (`node:fs` + `node:path` only): at this token
// count a single readable script is easier to read, debug, and vendor than
// Style Dictionary plus a build pipeline. Node >=24 strips TypeScript types
// natively, so that stays true at zero cost — no loader, no bundler, no
// devDependency. The price is that type-stripping cannot execute
// `enum`, `namespace`, or constructor parameter properties; `erasableSyntaxOnly`
// in `tsconfig.base.json` is what turns that into a typecheck error instead of
// a runtime one.

import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';

const TOKENS_PATH = 'packages/insolvia_tokens/tokens.json';
const TOKENS_README = 'packages/insolvia_tokens/README.md';
const REGEN_COMMAND = 'npm run tokens';

// The two banners differ, deliberately — this is not an oversight to tidy up.
//
// `theme.css` lands inside `insolvia_design_system`, a version-gated published
// package, so its bytes are expensive: rewriting one would drag an otherwise
// unrelated change into design-system-PR territory (own PR + version bump) for
// no user-visible gain. Naming the README rather than a command keeps the
// banner toolchain-agnostic: the generator and the way it is invoked can
// change without rewriting a single generated byte.
const CSS_BANNER =
  `/* DO NOT EDIT — generated from ${TOKENS_PATH}\n` + ` * Regenerate: see ${TOKENS_README}\n */\n`;

// `src/tokens.ts` lives in this package, which is neither published nor
// version-gated, so its banner is free to name a command.
const TS_BANNER =
  `// DO NOT EDIT — generated from ${TOKENS_PATH}\n` + `// Regenerate with: ${REGEN_COMMAND}\n`;

const CSS_OUT = 'packages/insolvia_design_system/src/styles/theme.css';
const TS_OUT = 'packages/insolvia_tokens/src/tokens.ts';

// Cognito's managed-login branding: the colours of the hosted sign-in page.
//
// This output is RECONCILED, not rendered from scratch, and it is the only one
// of the three that reads its own previous contents. The document is AWS's
// schema — layout, border radii, `enabled` flags, which auth methods appear —
// and that structure is owned by the console's branding editor, exported when
// it changes. Only the colour slots below belong to us. So the generator
// rewrites those slots in place and leaves everything else untouched, which
// makes it idempotent: reconciling an already-reconciled file is a no-op, and
// `--check` therefore asks exactly the right question — "do this file's colours
// still match the tokens?" — without caring about structure it does not own.
//
// No banner: the file is JSON, which has no comment syntax, and AWS rejects
// unknown keys so a "_comment" field cannot be smuggled in. The DO-NOT-EDIT
// warning lives in infra/modules/auth/main.tf beside the resource instead.
const COGNITO_OUT = 'infra/modules/auth/managed-login-settings.json';

/**
 * Colour slots in the managed-login document, each mapped to the semantic role
 * that owns it. Dotted paths under the document root; `{mode}` is substituted
 * with `lightMode`/`darkMode` and the role resolved in that mode.
 *
 * Semantic roles only — never palette names. That is the rule that makes a
 * re-brand a one-file change (see this package's CLAUDE.md), and it is why the
 * dark primary button is brass rather than the inverted white-on-navy a
 * hand-mapping would reach for: `semantic.primary.dark` already answers that
 * question, and the sign-in page must agree with the app rather than relitigate
 * it.
 */
const COGNITO_COLORS: ReadonlyArray<readonly [string, string]> = [
  // Primary button — the "Sign in" call to action.
  ['components.primaryButton.{mode}.defaults.backgroundColor', 'primary'],
  ['components.primaryButton.{mode}.defaults.textColor', 'primaryText'],
  ['components.primaryButton.{mode}.hover.backgroundColor', 'primaryHover'],
  ['components.primaryButton.{mode}.hover.textColor', 'primaryText'],
  ['components.primaryButton.{mode}.active.backgroundColor', 'primaryActive'],
  ['components.primaryButton.{mode}.active.textColor', 'primaryText'],
  ['components.primaryButton.{mode}.disabled.backgroundColor', 'muted'],
  ['components.primaryButton.{mode}.disabled.borderColor', 'muted'],

  // Secondary button, and the identity-provider buttons that share its shape.
  // No federated providers are configured, so the IdP ones never render today;
  // mapped anyway so enabling one later cannot surface AWS blue.
  ['components.secondaryButton.{mode}.defaults.backgroundColor', 'card'],
  ['components.secondaryButton.{mode}.defaults.borderColor', 'primary'],
  ['components.secondaryButton.{mode}.defaults.textColor', 'primary'],
  ['components.secondaryButton.{mode}.hover.backgroundColor', 'surfaceAlt'],
  ['components.secondaryButton.{mode}.hover.borderColor', 'primaryHover'],
  ['components.secondaryButton.{mode}.hover.textColor', 'primaryHover'],
  ['components.secondaryButton.{mode}.active.backgroundColor', 'surfaceAlt'],
  ['components.secondaryButton.{mode}.active.borderColor', 'primaryActive'],
  ['components.secondaryButton.{mode}.active.textColor', 'primaryActive'],
  ['components.idpButton.standard.{mode}.defaults.backgroundColor', 'card'],
  ['components.idpButton.standard.{mode}.defaults.borderColor', 'line'],
  ['components.idpButton.standard.{mode}.defaults.textColor', 'ink'],
  ['components.idpButton.standard.{mode}.hover.backgroundColor', 'surfaceAlt'],
  ['components.idpButton.standard.{mode}.hover.borderColor', 'primary'],
  ['components.idpButton.standard.{mode}.hover.textColor', 'ink'],
  ['components.idpButton.standard.{mode}.active.backgroundColor', 'surfaceAlt'],
  ['components.idpButton.standard.{mode}.active.borderColor', 'primaryActive'],
  ['components.idpButton.standard.{mode}.active.textColor', 'ink'],

  // Page and form surfaces.
  ['components.pageBackground.{mode}.color', 'bg'],
  ['components.form.{mode}.backgroundColor', 'card'],
  ['components.form.{mode}.borderColor', 'line'],
  ['components.pageHeader.{mode}.background.color', 'surfaceAlt'],
  ['components.pageHeader.{mode}.borderColor', 'line'],
  ['components.pageFooter.{mode}.background.color', 'surfaceAlt'],
  ['components.pageFooter.{mode}.borderColor', 'line'],

  // Text.
  ['components.pageText.{mode}.headingColor', 'ink'],
  ['components.pageText.{mode}.bodyColor', 'ink'],
  ['components.pageText.{mode}.descriptionColor', 'muted'],

  // Inputs, labels, and the focus ring — the keyboard-navigation affordance,
  // which was still AWS blue in both modes before this existed.
  ['componentClasses.input.{mode}.defaults.backgroundColor', 'card'],
  ['componentClasses.input.{mode}.defaults.borderColor', 'line'],
  ['componentClasses.input.{mode}.placeholderColor', 'muted'],
  ['componentClasses.inputLabel.{mode}.textColor', 'ink'],
  ['componentClasses.inputDescription.{mode}.textColor', 'muted'],
  ['componentClasses.focusState.{mode}.borderColor', 'primary'],
  ['componentClasses.divider.{mode}.borderColor', 'line'],

  // Links — "Forgot your password?".
  ['componentClasses.link.{mode}.defaults.textColor', 'primary'],
  ['componentClasses.link.{mode}.hover.textColor', 'primaryHover'],

  // Selection controls and the dropdown.
  ['componentClasses.optionControls.{mode}.defaults.backgroundColor', 'card'],
  ['componentClasses.optionControls.{mode}.defaults.borderColor', 'line'],
  ['componentClasses.optionControls.{mode}.selected.backgroundColor', 'primary'],
  ['componentClasses.optionControls.{mode}.selected.foregroundColor', 'primaryText'],
  ['componentClasses.dropDown.{mode}.defaults.itemBackgroundColor', 'card'],
  ['componentClasses.dropDown.{mode}.hover.itemBackgroundColor', 'surfaceAlt'],
  ['componentClasses.dropDown.{mode}.hover.itemTextColor', 'ink'],
  ['componentClasses.dropDown.{mode}.hover.itemBorderColor', 'line'],
  ['componentClasses.dropDown.{mode}.match.itemTextColor', 'primary'],

  // Status. `success`/`warning`/`danger` carry their own semantic roles, so a
  // re-brand moves them too rather than leaving AWS's red and amber behind.
  ['componentClasses.statusIndicator.{mode}.error.indicatorColor', 'danger'],
  ['componentClasses.statusIndicator.{mode}.error.borderColor', 'danger'],
  ['componentClasses.statusIndicator.{mode}.success.indicatorColor', 'success'],
  ['componentClasses.statusIndicator.{mode}.success.borderColor', 'success'],
  ['componentClasses.statusIndicator.{mode}.warning.indicatorColor', 'warning'],
  ['componentClasses.statusIndicator.{mode}.warning.borderColor', 'warning'],
  ['components.alert.{mode}.error.borderColor', 'danger'],
];

/** The brightnesses every semantic token must declare a value for. */
const MODES = ['light', 'dark'] as const;
type Mode = (typeof MODES)[number];

function main(args: string[]): void {
  const check = args.includes('--check');
  const root = repoRoot();

  const source = readFileSync(join(root, TOKENS_PATH), 'utf8');
  const tokens = asObject(JSON.parse(source) as JsonValue, TOKENS_PATH);

  const outputs: Array<readonly [string, string]> = [
    [CSS_OUT, renderCss(tokens)],
    [TS_OUT, renderTypeScript(tokens)],
  ];

  // Reconciled rather than rendered, so it needs its current contents as input.
  // Absent (a fresh checkout of infra, or the file deliberately removed) is not
  // an error — there is simply nothing to reconcile.
  const cognitoCurrent = readIfExists(join(root, COGNITO_OUT));
  if (cognitoCurrent !== null) {
    outputs.push([COGNITO_OUT, renderCognitoBranding(tokens, cognitoCurrent)]);
  }

  const drifted: string[] = [];
  for (const [path, contents] of outputs) {
    const file = join(root, path);
    const current = readIfExists(file);
    if (current === contents) continue;
    if (check) {
      drifted.push(path);
    } else {
      mkdirSync(dirname(file), { recursive: true });
      writeFileSync(file, contents);
      process.stdout.write(`wrote ${path}\n`);
    }
  }

  if (!check) {
    process.stdout.write(`Generated ${outputs.length} file(s) from ${TOKENS_PATH}.\n`);
    return;
  }

  if (drifted.length === 0) {
    process.stdout.write(`Tokens are in sync (${outputs.length} file(s) checked).\n`);
    return;
  }

  process.stderr.write(`Generated token output has drifted from ${TOKENS_PATH}:\n`);
  for (const path of drifted) {
    process.stderr.write(`  - ${path}\n`);
  }
  process.stderr.write(`\nEdit ${TOKENS_PATH} (never the generated file), then run:\n`);
  process.stderr.write(`  ${REGEN_COMMAND}\n`);
  process.exitCode = 1;
}

/**
 * The script lives at `<root>/packages/insolvia_tokens/tool/`, so the repo
 * root is three directories up — resolved from the module's own location
 * rather than the cwd so the generator behaves identically from anywhere.
 */
function repoRoot(): string {
  return resolve(import.meta.dirname, '..', '..', '..');
}

function readIfExists(file: string): string | null {
  try {
    return readFileSync(file, 'utf8');
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code === 'ENOENT') return null;
    throw error;
  }
}

// ─────────────────────────── token model ───────────────────────────

type JsonValue = string | number | boolean | null | JsonValue[] | { [key: string]: JsonValue };
type JsonObject = { [key: string]: JsonValue };

/**
 * One token, as a `[name, body]` pair.
 *
 * An array rather than a `Map`/object, on purpose: emission order is part of
 * the output bytes, and JavaScript reorders integer-like keys of a plain
 * object ahead of the rest. Every token name is a non-numeric identifier
 * today, but pairs make the ordering guarantee structural instead of lucky.
 */
type TokenEntry = readonly [string, JsonObject];

function asObject(value: JsonValue | undefined, where: string): JsonObject {
  if (typeof value !== 'object' || value === null || Array.isArray(value)) {
    throw new Error(`Expected an object at ${where}, got ${JSON.stringify(value)}`);
  }
  return value;
}

function asString(value: JsonValue | undefined, where: string): string {
  if (typeof value !== 'string') {
    throw new Error(`Expected a string at ${where}, got ${JSON.stringify(value)}`);
  }
  return value;
}

function asNumber(value: JsonValue | undefined, where: string): number {
  if (typeof value !== 'number' || !Number.isFinite(value)) {
    throw new Error(`Expected a number at ${where}, got ${JSON.stringify(value)}`);
  }
  return value;
}

/**
 * Entries whose key starts with `$` are documentation for humans reading the
 * JSON, not tokens.
 */
function group(tokens: JsonObject, name: string): TokenEntry[] {
  const raw = asObject(tokens[name], name);
  return Object.entries(raw)
    .filter(([key]) => !key.startsWith('$'))
    .map(([key, value]) => [key, asObject(value, `${name}.${key}`)] as const);
}

/** Resolves a `{palette.foo}` alias to its raw hex value. */
function resolveAlias(tokens: JsonObject, ref: string): string {
  if (!ref.startsWith('{') || !ref.endsWith('}')) return ref;
  let node: JsonValue = tokens;
  for (const part of ref.slice(1, -1).split('.')) {
    // Annotated, not inferred: `node` is reassigned from `next` at the end of
    // the loop body, so inference here would be circular (TS7022).
    const next: JsonValue | undefined = asObject(node, ref)[part];
    if (next === undefined || next === null) {
      throw new Error(`Unresolvable token alias: ${ref}`);
    }
    node = next;
  }
  return asString(asObject(node, ref)['value'], `${ref}.value`);
}

type Rgba = readonly [number, number, number, number];

/** `#RRGGBB` or `#RRGGBBAA` → `[r, g, b, a]`, each 0-255. */
function parseHex(hex: string): Rgba {
  const body = hex.replace('#', '');
  // `parseInt` would happily stop at the first bad character and return a
  // plausible-looking number for a typo'd hex, so the shape is validated up
  // front instead of trusting the parse below to fail.
  if ((body.length !== 6 && body.length !== 8) || !/^[0-9a-fA-F]+$/.test(body)) {
    throw new Error(`Expected #RRGGBB or #RRGGBBAA, got "${hex}"`);
  }
  return [
    parseInt(body.slice(0, 2), 16),
    parseInt(body.slice(2, 4), 16),
    parseInt(body.slice(4, 6), 16),
    body.length === 8 ? parseInt(body.slice(6, 8), 16) : 255,
  ];
}

/**
 * Rounds half AWAY FROM ZERO, which `Math.round` does not: it breaks ties
 * toward +Infinity, so the two disagree on every negative half
 * (`Math.round(-0.5)` is `-0`, this is `-1`). Channel blends are never negative
 * today, so the two agree in practice — but this function is what makes a
 * pre-computed blend land on the same pixel the browser does, so the rounding
 * rule is stated explicitly rather than inherited from whatever `Math.round`
 * happens to do at the edges.
 */
function roundHalfAwayFromZero(value: number): number {
  return value < 0 ? -Math.round(-value) : Math.round(value);
}

/**
 * The sRGB blend CSS `color-mix(in srgb, <base> <100-amount>%, <mix> <amount>%)`
 * produces, pre-computed so the React Native side matches the browser exactly.
 */
function mix(baseHex: string, mixName: string, amount: number): string {
  const [br, bg, bb, ba] = parseHex(baseHex);
  const [mr, mg, mb, ma] =
    mixName === 'white' ? ([255, 255, 255, 255] as const) : ([0, 0, 0, 255] as const);
  const t = amount / 100;
  const out: Rgba = [
    roundHalfAwayFromZero(br * (1 - t) + mr * t),
    roundHalfAwayFromZero(bg * (1 - t) + mg * t),
    roundHalfAwayFromZero(bb * (1 - t) + mb * t),
    roundHalfAwayFromZero(ba * (1 - t) + ma * t),
  ];
  const hex = out.map((channel) => channel.toString(16).padStart(2, '0')).join('');
  return `#${hex.slice(0, 6).toUpperCase()}${out[3] === 255 ? '' : hex.slice(6).toUpperCase()}`;
}

/** Resolves every semantic + derived token for one brightness. */
function valuesFor(tokens: JsonObject, mode: Mode): Map<string, string> {
  const resolved = new Map<string, string>();
  for (const [name, body] of group(tokens, 'semantic')) {
    resolved.set(name, resolveAlias(tokens, asString(body[mode], `semantic.${name}.${mode}`)));
  }
  for (const [name, body] of group(tokens, 'semanticDerived')) {
    const from = asString(body['from'], `semanticDerived.${name}.from`);
    const base = resolved.get(from);
    if (base === undefined) {
      throw new Error(`semanticDerived.${name} derives from unknown semantic "${from}"`);
    }
    const spec = asObject(body[mode], `semanticDerived.${name}.${mode}`);
    resolved.set(
      name,
      mix(
        base,
        asString(spec['mix'], `semanticDerived.${name}.${mode}.mix`),
        asNumber(spec['amount'], `semanticDerived.${name}.${mode}.amount`),
      ),
    );
  }
  return resolved;
}

function lookup(values: Map<string, string>, name: string): string {
  const value = values.get(name);
  if (value === undefined) throw new Error(`No resolved value for "${name}"`);
  return value;
}

/**
 * Rewrite the colour slots of Cognito's managed-login settings from the
 * semantic tokens, leaving every other key exactly as found.
 *
 * A path that does not exist in the document is a hard error, not a skip: it
 * means AWS changed its schema (or a console re-export dropped a component),
 * and silently branding fewer things than intended is precisely the failure
 * this generator exists to prevent — the sign-in page would quietly regain a
 * patch of AWS blue and nothing would say so.
 */
function renderCognitoBranding(tokens: JsonObject, current: string): string {
  const document = JSON.parse(current) as JsonValue;
  const root = asObject(document, COGNITO_OUT);

  for (const mode of MODES) {
    const values = valuesFor(tokens, mode);
    const key = mode === 'light' ? 'lightMode' : 'darkMode';
    for (const [template, role] of COGNITO_COLORS) {
      setColor(
        root,
        template.replace('{mode}', key).split('.'),
        cognitoColor(lookup(values, role)),
      );
    }
  }

  return `${JSON.stringify(root, null, 2)}\n`;
}

/** Walk a dotted path and assign, asserting every segment exists. */
function setColor(root: JsonObject, path: readonly string[], value: string): void {
  let node: JsonObject = root;
  for (let index = 0; index < path.length - 1; index += 1) {
    const segment = path[index] as string;
    if (!(segment in node)) {
      throw new Error(`${COGNITO_OUT}: no such path segment "${segment}" in ${path.join('.')}`);
    }
    node = asObject(node[segment], `${COGNITO_OUT}:${path.slice(0, index + 1).join('.')}`);
  }
  const leaf = path[path.length - 1] as string;
  if (!(leaf in node)) {
    throw new Error(`${COGNITO_OUT}: no such colour slot "${path.join('.')}"`);
  }
  node[leaf] = value;
}

/**
 * Cognito wants `rrggbbaa` with no leading `#`, lower-cased for stability —
 * the console writes mixed case and a diff should reflect a real colour change,
 * not a round trip through the branding editor.
 */
function cognitoColor(hex: string): string {
  const bare = hex.replace('#', '').toLowerCase();
  return bare.length === 8 ? bare : `${bare}ff`;
}

// ─────────────────────────── output buffer ───────────────────────────

/** The append-only string buffer each output is built with. */
class Out {
  #parts: string[] = [];

  write(text: string): void {
    this.#parts.push(text);
  }

  writeln(text = ''): void {
    this.#parts.push(text, '\n');
  }

  toString(): string {
    return this.#parts.join('');
  }
}

// ─────────────────────────── CSS output ───────────────────────────

function kebab(name: string): string {
  return name.replace(/[A-Z]/g, (letter) => `-${letter.toLowerCase()}`).replace(/-+/g, '-');
}

/**
 * Opaque colors stay hex; translucent ones become `rgb(r g b / a)`, which is
 * how the reference design system authors alpha.
 */
function cssColor(hex: string): string {
  const [r, g, b, a] = parseHex(hex);
  const rgb = hex.replace('#', '').slice(0, 6).toLowerCase();
  if (a === 255) {
    return `#${rgb}`;
  }
  return `rgb(${r} ${g} ${b} / ${trim(a / 255)})`;
}

function renderCss(tokens: JsonObject): string {
  const semantic = group(tokens, 'semantic');
  const derived = group(tokens, 'semanticDerived');
  const out = new Out();
  out.write(CSS_BANNER);
  out.writeln(`/*
 * Tailwind v4 design tokens for Insolvia's React/web surfaces.
 *
 * Consuming apps import this from their Tailwind v4 CSS entrypoint:
 *
 *   @import "tailwindcss";
 *   @import "@insolvia-ai/design-system/theme.css";
 *
 * Dark mode is toggled by setting \`data-theme="dark"\` on a root element
 * (e.g. <html data-theme="dark">) — every component reads the SEMANTIC
 * tokens below, so nothing in component source changes per theme.
 *
 * Brand yourself by overriding the semantic variables after importing this
 * file. Never depend on raw palette names (ink/brass/paper): they are an
 * implementation detail of the default mapping and are not emitted here.
 */`);
  out.writeln();
  out.writeln('@theme {');

  const section = (comment: string): void => {
    out.writeln();
    out.writeln(`  /* ${comment} */`);
  };

  section('Typography. Apps can override these to apply their own brand.');
  for (const [name, body] of group(tokens, 'fonts')) {
    out.writeln(`  --font-${kebab(name)}: ${asString(body['value'], `fonts.${name}.value`)};`);
  }

  section('Semantic colors — the light-mode default mapping.');
  for (const [name, body] of semantic) {
    const value = resolveAlias(tokens, asString(body['light'], `semantic.${name}.light`));
    out.writeln(`  --color-${kebab(name)}: ${cssColor(value)};`);
  }

  section('Derived states. Overriding the base semantic moves these too.');
  for (const [name, body] of derived) {
    const spec = asObject(body['light'], `semanticDerived.${name}.light`);
    const from = asString(body['from'], `semanticDerived.${name}.from`);
    out.writeln(`  --color-${kebab(name)}: ${colorMix(from, spec, name)};`);
  }

  section('Spacing — a 4pt base grid.');
  for (const [name, body] of group(tokens, 'spacing')) {
    const rem = asNumber(body['value'], `spacing.${name}.value`) / 16;
    out.writeln(`  --spacing-${kebab(name)}: ${trim(rem)}rem;`);
  }

  section('Corner radii.');
  for (const [name, body] of group(tokens, 'radii')) {
    out.writeln(`  --radius-${kebab(name)}: ${asString(body['css'], `radii.${name}.css`)};`);
  }

  section('Elevation.');
  for (const [name, body] of group(tokens, 'shadows')) {
    out.writeln(`  --shadow-${kebab(name)}: ${asString(body['value'], `shadows.${name}.value`)};`);
  }

  out.writeln('}');
  out.writeln();
  out.writeln("[data-theme='dark'] {");

  for (const [name, body] of semantic) {
    const value = resolveAlias(tokens, asString(body['dark'], `semantic.${name}.dark`));
    out.writeln(`  --color-${kebab(name)}: ${cssColor(value)};`);
  }
  out.writeln();
  for (const [name, body] of derived) {
    const spec = asObject(body['dark'], `semanticDerived.${name}.dark`);
    const from = asString(body['from'], `semanticDerived.${name}.from`);
    out.writeln(`  --color-${kebab(name)}: ${colorMix(from, spec, name)};`);
  }

  out.writeln('}');
  return out.toString();
}

function colorMix(from: string, spec: JsonObject, where: string): string {
  const amount = asNumber(spec['amount'], `semanticDerived.${where}.amount`);
  const mixName = asString(spec['mix'], `semanticDerived.${where}.mix`);
  return (
    `color-mix(in srgb, var(--color-${kebab(from)}) ${100 - amount}%, ` + `${mixName} ${amount}%)`
  );
}

function trim(value: number): string {
  // Four decimal places, then trailing zeros stripped. `toFixed` rounds half
  // away from zero for a positive value (0.03125 → "0.0313"), matching `mix`.
  const text = value.toFixed(4);
  return text.includes('.') ? text.replace(/0+$/, '').replace(/\.$/, '') : text;
}

// ─────────────────────────── TypeScript output ───────────────────────────

/**
 * Renders a JavaScript string literal the way Prettier would.
 *
 * `src/tokens.ts` sits inside the `prettier --check` target, so the generator
 * has to agree with Prettier byte for byte — including its quote choice, which
 * is whichever quote needs fewer escapes (single on a tie).
 */
function jsString(value: string): string {
  const singles = (value.match(/'/g) ?? []).length;
  const doubles = (value.match(/"/g) ?? []).length;
  const quote = singles > doubles ? '"' : "'";
  const escaped = value.replace(/\\/g, '\\\\').split(quote).join(`\\${quote}`);
  return `${quote}${escaped}${quote}`;
}

function tsDoc(description: string, indent = '  '): string {
  if (description.includes('*/')) {
    throw new Error(`Token description cannot contain "*/": ${description}`);
  }
  return `${indent}/** ${description} */\n`;
}

/**
 * The value the React Native app consumes: `#RRGGBB`, or `#RRGGBBAA` when the
 * token carries alpha. Re-rendered from the parsed channels rather than passed
 * through, so an alias authored in lowercase and a `mix()` result cannot end
 * up in the same file spelled two different ways.
 */
function rnColor(hex: string): string {
  const [r, g, b, a] = parseHex(hex);
  const channels = [r, g, b, ...(a === 255 ? [] : [a])];
  return `#${channels
    .map((c) => c.toString(16).padStart(2, '0'))
    .join('')
    .toUpperCase()}`;
}

function renderTypeScript(tokens: JsonObject): string {
  const semantic = group(tokens, 'semantic');
  const derived = group(tokens, 'semanticDerived');
  const entries = [...semantic, ...derived];

  const out = new Out();
  out.write(TS_BANNER);
  out.writeln();
  out.writeln('/**');
  out.writeln(' * Design tokens for the React Native app, consumed as `@insolvia-ai/tokens`');
  out.writeln(' * and used with `StyleSheet.create`.');
  out.writeln(' *');
  out.writeln(' * Plain exported consts — no CSS, no Tailwind, no runtime, no dependencies.');
  out.writeln(' *');
  out.writeln(' * Colors are the SEMANTIC layer only. The raw palette (ink/brass/paper) is');
  out.writeln(' * deliberately absent rather than merely discouraged: nothing here exports');
  out.writeln(' * it, so UI code cannot couple to it by accident and a re-brand stays a');
  out.writeln(' * one-file change.');
  out.writeln(' *');
  out.writeln(' * Derived states are pre-computed with the same sRGB blend that `theme.css`');
  out.writeln(' * expresses as `color-mix(in srgb, ...)`. The browser defers that blend and');
  out.writeln(' * React Native cannot, so it is resolved here — both stacks land on the');
  out.writeln(' * same pixel.');
  out.writeln(' */');
  out.writeln();

  out.writeln('/** A color scheme the app can render. Every one is declared in `colors`. */');
  out.writeln(`export type ColorSchemeName = ${MODES.map(jsString).join(' | ')};`);
  out.writeln();

  out.writeln('/**');
  out.writeln(' * One complete mapping of semantic role onto an sRGB value.');
  out.writeln(' *');
  out.writeln(' * Every member is required, so a scheme that omits one — a missing');
  out.writeln(' * dark-mode value — is a compile error, never a silent fallback.');
  out.writeln(' */');
  out.writeln('export interface ColorScheme {');
  let first = true;
  for (const [name, body] of entries) {
    if (!first) out.writeln();
    first = false;
    out.write(tsDoc(asString(body['description'], `${name}.description`)));
    out.writeln(`  readonly ${name}: string;`);
  }
  out.writeln('}');
  out.writeln();

  out.writeln('/** The semantic color vocabulary — the only color names UI code speaks. */');
  out.writeln('export type SemanticColorName = keyof ColorScheme;');
  out.writeln();

  out.writeln('/** Every semantic color, per scheme. */');
  out.writeln('export const colors = {');
  for (const mode of MODES) {
    const values = valuesFor(tokens, mode);
    if (mode !== MODES[0]) out.writeln();
    out.write(tsDoc(`The ${mode}-mode mapping of palette onto semantics.`));
    out.writeln(`  ${mode}: {`);
    for (const [name] of entries) {
      out.writeln(`    ${name}: ${jsString(rnColor(lookup(values, name)))},`);
    }
    out.writeln('  },');
  }
  out.writeln('} as const satisfies Record<ColorSchemeName, ColorScheme>;');
  out.writeln();

  out.writeln('/**');
  out.writeln(' * Exhaustiveness guard, in the spirit of the no-default-arm switches in');
  out.writeln(' * `apps/insolvia_app/src/config/environment.ts`: naming a scheme in');
  out.writeln(' * `ColorSchemeName` without declaring its colors above stops compiling');
  out.writeln(' * rather than resolving to `undefined` at runtime.');
  out.writeln(' */');
  // `DeclaredScheme` is not just a readability alias: it is what keeps the
  // conditional type below inside Prettier's 100-column budget on one line.
  // `src/tokens.ts` is inside the `prettier --check` target, so a line Prettier
  // would re-wrap is a CI failure on a file no human wrote.
  //
  // The tuple wrappers are load-bearing too: a bare `Exclude<…> extends never`
  // distributes over `never` and resolves to `never`, which would make the
  // guard fail even when it should pass.
  out.writeln('type DeclaredScheme = keyof typeof colors;');
  out.writeln(
    'type SchemesExhaustive = [Exclude<ColorSchemeName, DeclaredScheme>] extends [never] ? true : never;',
  );
  out.writeln('const _schemesAreExhaustive: SchemesExhaustive = true;');
  out.writeln();

  renderTsRecord(out, tokens, {
    group: 'spacing',
    interfaceName: 'Spacing',
    keyType: 'SpacingStep',
    constName: 'spacing',
    valueType: 'number',
    interfaceDoc: [
      'Spacing scale — a 4pt base grid. Use these instead of magic numbers so',
      'layout rhythm stays consistent across every Insolvia surface.',
    ],
    keyDoc: 'A step on the spacing scale.',
    value: (body, where) => String(asNumber(body['value'], where)),
  });
  out.writeln();

  renderTsRecord(out, tokens, {
    group: 'radii',
    interfaceName: 'Radii',
    keyType: 'RadiusName',
    constName: 'radii',
    valueType: 'number',
    interfaceDoc: [
      'Corner-radius scale, in density-independent pixels — the unit React',
      "Native's `borderRadius` already speaks.",
    ],
    keyDoc: 'A step on the corner-radius scale.',
    value: (body, where) => String(asNumber(body['value'], where)),
  });
  out.writeln();

  renderTsRecord(out, tokens, {
    group: 'fonts',
    interfaceName: 'Typography',
    keyType: 'FontRole',
    constName: 'typography',
    valueType: 'string',
    interfaceDoc: [
      'Type families, as authored: the same CSS family stacks the web surfaces',
      'use. React Native resolves a single registered family, so until the brand',
      'fonts land (O4) both roles fall back to the platform UI font — which is',
      'exactly where the web stacks are today.',
    ],
    keyDoc: 'A type role.',
    value: (body, where) => jsString(asString(body['value'], where)),
  });

  return out.toString();
}

/** Shared shape for the non-color token groups: interface, key type, const. */
function renderTsRecord(
  out: Out,
  tokens: JsonObject,
  spec: {
    group: string;
    interfaceName: string;
    keyType: string;
    constName: string;
    valueType: string;
    interfaceDoc: string[];
    keyDoc: string;
    value: (body: JsonObject, where: string) => string;
  },
): void {
  const entries = group(tokens, spec.group);

  out.writeln('/**');
  for (const line of spec.interfaceDoc) {
    out.writeln(` * ${line}`);
  }
  out.writeln(' */');
  out.writeln(`export interface ${spec.interfaceName} {`);
  let first = true;
  for (const [name, body] of entries) {
    if (!first) out.writeln();
    first = false;
    out.write(tsDoc(asString(body['description'], `${spec.group}.${name}.description`)));
    out.writeln(`  readonly ${name}: ${spec.valueType};`);
  }
  out.writeln('}');
  out.writeln();

  out.writeln(`/** ${spec.keyDoc} */`);
  out.writeln(`export type ${spec.keyType} = keyof ${spec.interfaceName};`);
  out.writeln();

  out.writeln(`export const ${spec.constName} = {`);
  for (const [name, body] of entries) {
    out.writeln(`  ${name}: ${spec.value(body, `${spec.group}.${name}.value`)},`);
  }
  out.writeln(`} as const satisfies ${spec.interfaceName};`);
}

main(process.argv.slice(2));
